plot(xmr[,'date'], xmr[,'close'], type = 'l')
par(new=TRUE)
plot(xmr_trend[,'date'], xmr_trend[,'hits'], type = 'l', col = 'green')
par(new=TRUE)
plot(xmr_buy[,'date'], xmr_buy[,'price'], col = 'blue')
par(new=TRUE)
plot(xmr_sell[,'date'], xmr_sell[,'price'], col = 'red')
