plot(eth[,'date'], eth[,'close'], type = 'l')
par(new=TRUE)
plot(eth_vol[,'date'], eth_vol[,'volume'], type = 'l', col = 'green')
##par(new=TRUE)
##plot(btc_buy[,'date'], btc_buy[,'price'], col = 'blue')
##par(new=TRUE)
##plot(btc_sell[,'date'], btc_sell[,'price'], col = 'red')
