plot(btc[,'date'], btc[,'close'], type = 'l')
par(new=TRUE)
plot(btc_trend[,'date'], btc_trend[,'hits'], type = 'l', col = 'green')
par(new=TRUE)
plot(btc_buy[,'date'], btc_buy[,'price'], col = 'blue')
par(new=TRUE)
plot(btc_sell[,'date'], btc_sell[,'price'], col = 'red')
