##plot(btc[,'date'], btc[,'close'], type = 'l')
##par(new=TRUE)
plot(btc_boll_low[,'date'], btc_boll_low[,'value'], type = 'l', col = 'red')
par(new=TRUE)
plot(btc_boll_high[,'date'], btc_boll_high[,'value'], type = 'l', col = 'green')
##par(new=TRUE)
##plot(btc_buy[,'date'], btc_buy[,'price'], col = 'blue')
##par(new=TRUE)
##plot(btc_sell[,'date'], btc_sell[,'price'], col = 'red')
